### PR TITLE
adding Sposorship Exploration task force information

### PR DESCRIPTION
**Pull request by tracykteal**
This is a delayed posting of the Sponsorship Exploration Task Force, moving information over from a Google document. 

Needs review from @zjsteyn @rgaiacs @brownsarahm

### CODE REVIEW

**Comment by rgaiacs** [comment]
Thanks for the pull request.

@tracykteal Can you remove `2019/sponsorship-exploration/sponsorship-exploration-project-charter.md~`? It is a backup copy from Emacs. :-D

Context, Objective and Deliverables looks good to me.

**Comment by tracykteal** [comment]
Ah, yes, thanks. Remove the emacs backup file. Thanks for the review on Context, Objectives and Deliverables.

**Comment by brownsarahm** [comment]
This looks good to me, content wise.  If it should follow the style guide there are a few small things (US spellings & missing oxford comma) that could be fixed.

**Comment by kariljordan** [comment]
Hi:) I wanted to check in on this PR and ask if the report is still coming out on 15-January. @sheraaronhurt is working on a CarpentryCon Sponsorship model this quarter, and I believe the information from your report may help her. Please advise. 

cc @ErinBecker

**Comment by tracykteal** [comment]
Thanks @kariljordan. I've given the Task Force until today to provide comments. So we'll be merging the PR and posting tomorrow.

**Comment by tracykteal** [comment]
I made some spelling changes as per style guide. This has been reviewed and is now ready to be merged @kariljordan.

**Comment by kariljordan** [comment]
Thanks so much Tracy!

**Pull request merged**
